Resources:
  CodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties: 
      Name: ${self:service.name}
      Description: This is the codebuild project for the ${env:APP_NAME}
      ServiceRole:
        Fn::GetAtt:
          - cicdRole
          - Arn
      Artifacts:
        Type: CODEPIPELINE
        Name: ${self:service.name}-build
        Packaging: NONE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:4.0'
        EnvironmentVariables:
          - Name: GITHUB_TOKEN
            Value: ${env:GITHUB_TOKEN}
          - Name: NODE_ENV
            Value: ${env:NODE_ENV}
          - Name: AWS_ACCESS_KEY_ID
            Value: ${env:AWS_ACCESS_KEY_ID}
          - Name: AWS_SECRET_ACCESS_KEY
            Value: ${env:AWS_SECRET_ACCESS_KEY}
          - Name: AWS_PROFILE
            Value: ${env:AWS_PROFILE}
          - Name: REGION
            Value: ${env:REGION}
          - Name: WEBASG
            Value: ${env:ASG_NAME_WEB}
          - Name: APPASG
            Value: ${env:ASG_NAME_APP}
      Source:
        Type: CODEPIPELINE
 