Resources:
  MyAccelerator:
    Type: AWS::GlobalAccelerator::Accelerator
    Properties:
      Name: GlobalAccelerator
      IpAddressType: IPV4
      Enabled: true
  MyListener:
    Type: AWS::GlobalAccelerator::Listener
    Properties:
      AcceleratorArn: !Ref MyAccelerator
      Protocol: TCP
      ClientAffinity: SOURCE_IP
      PortRanges:
      - FromPort: 80
        ToPort: 80
      - FromPort: 443
        ToPort: 443
  Ireland:
    Type: AWS::GlobalAccelerator::EndpointGroup
    Properties:
      ListenerArn: !Ref MyListener
      EndpointGroupRegion: ${env:IRELAND}
      EndpointConfigurations:
        - EndpointId: ${cf.${env:IRELAND}:${env:STAGE}-${env:IRELAND}-${env:APP_NAME}-stack.WebAlb}
          Weight: 100
      HealthCheckPort: 443
      HealthCheckProtocol: TCP
      HealthCheckPath: “/”
      ThresholdCount: 5
      HealthCheckIntervalSeconds: 10
  Oregon:
    Type: AWS::GlobalAccelerator::EndpointGroup
    Properties:
      ListenerArn: !Ref MyListener
      EndpointGroupRegion: ${env:OREGON}
      EndpointConfigurations:
        - EndpointId: ${cf.${env:OREGON}:${env:STAGE}-${env:OREGON}-${env:APP_NAME}-stack.WebAlb}
          Weight: 100
      HealthCheckPort: 443
      HealthCheckProtocol: TCP
      HealthCheckPath: “/”
      ThresholdCount: 5
      HealthCheckIntervalSeconds: 10
  Sydney:
    Type: AWS::GlobalAccelerator::EndpointGroup
    Properties:
      ListenerArn: !Ref MyListener
      EndpointGroupRegion: ${env:SYDNEY}
      EndpointConfigurations:
        - EndpointId: ${cf.${env:SYDNEY}:${env:STAGE}-${env:SYDNEY}-${env:APP_NAME}-stack.WebAlb}
          Weight: 100
      HealthCheckPort: 443
      HealthCheckProtocol: TCP
      HealthCheckPath: “/”
      ThresholdCount: 5
      HealthCheckIntervalSeconds: 10