version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12  
    commands:
      - echo Configuring AWS Profile...
      - npm install -g serverless --unsafe-perm
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile $AWS_PROFILE -o
  build:
    commands:
      - echo Copying apps to respective S3 buckets at `date`
      - aws s3 sync apps/Web s3://$WEB_S3_BUCKET/App --profile $AWS_PROFILE --delete 
      - aws s3 sync apps/App s3://$APP_S3_BUCKET/App --profile $AWS_PROFILE --delete
  post_build:
    commands:
      - echo Initiating Auto-Scaling instance refresh at `date`
      - aws autoscaling start-instance-refresh --region $REGION --auto-scaling-group-name $REGION-web-asg
      - aws autoscaling start-instance-refresh --region $REGIOn --auto-scaling-group-name $REGION-app-asg
      - echo Deployed Successfully `date`