version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12  
    commands:
      - echo Installing serverless...
      - npm install -g serverless --unsafe-perm
      - echo Installing source NPM dependencies...
      - npm install
      - echo Configuring AWS Profile...
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile $AWS_PROFILE -o
  build:
    commands:
      - echo Serverless deploy started on $APP_NAME at `date`
      - npm run deploy:$NODE_ENV
      - aws s3 sync apps/Web s3://$WEB_S3_BUCKET/App --profile $AWS_PROFILE --delete 
      - aws s3 sync apps/APP s3://$APP_S3_BUCKET/App --profile $AWS_PROFILE --delete
      - aws autoscaling start-instance-refresh --auto-scaling-group-name $WEBASG
      - aws autoscaling start-instance-refresh --auto-scaling-group-name $APPASG
  post_build:
    commands:
      - echo Deployed Successfully `date`