Resources:
  WebAlbTg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckPath: /
      HealthCheckPort: 3333
      HealthCheckProtocol: HTTP
      Port: 3333
      Name: ${self:service.name}-web-tg
      Protocol: HTTP
      TargetType: instance
      VpcId: !Ref Vpc
  WebAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: ${env:APP_NAME}-web-alb
      Scheme: internet-facing
      SecurityGroups: 
      - Fn::GetAtt: 
          - WebAlbSg
          - GroupId
      Subnets: 
        - Ref: WebSubAz1
        - Ref: WebSubAz2
        - Ref: WebSubAz3
      Type: application
  WebHttpListener:
   Type: "AWS::ElasticLoadBalancingV2::Listener"
   Properties:
     DefaultActions:
       - Type: "redirect"
         RedirectConfig:
           Protocol: "HTTPS"
           Port: "443"
           Host: "#{host}"
           Path: "/#{path}"
           Query: "#{query}"
           StatusCode: "HTTP_301"
     LoadBalancerArn: !Ref WebAlb
     Port: 80
     Protocol: "HTTP"
  WebHttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref WebAlb
      Port: 443
      Protocol: HTTPS
      Certificates:
      - CertificateArn: !Ref WebAlbCert
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebAlbTg  
  AppAlbTg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckPath: /
      HealthCheckPort: 3333
      HealthCheckProtocol: HTTP
      Port: 3333
      Name: ${self:service.name}-app-tg
      Protocol: HTTP
      TargetType: instance
      VpcId: !Ref Vpc
  AppAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: ${env:APP_NAME}-app-alb
      Scheme: internal
      SecurityGroups: 
      - Fn::GetAtt: 
          - AppAlbSg
          - GroupId
      Subnets: 
        - Ref: AppSubAz1
        - Ref: AppSubAz2
        - Ref: AppSubAz3
      Type: application
  AppHttplistener:
   Type: "AWS::ElasticLoadBalancingV2::Listener"
   Properties:
     DefaultActions:
       - Type: "redirect"
         RedirectConfig:
           Protocol: "HTTPS"
           Port: "443"
           Host: "#{host}"
           Path: "/#{path}"
           Query: "#{query}"
           StatusCode: "HTTP_301"
     LoadBalancerArn: !Ref AppAlb
     Port: 80
     Protocol: "HTTP"
  AppHttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref AppAlb
      Port: 443
      Protocol: HTTPS
      Certificates:
      - CertificateArn: !Ref AppAlbCert
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AppAlbTg     
Outputs:
  WebAlb:
    Description: Web Alb ARN
    Value:
      Ref: WebAlb
    Export:
      Name: WebAlb
  AppAlb:
    Description: App Alb ARN
    Value:
      Ref: AppAlb
    Export:
      Name: AppAlb